# ------------------------------------------
# Site settings
# ------------------------------------------
title: "Climate and Health Lab"
email: eiyamba@knust.edu.gh
description: >
  PI: Edmund Ilimoan Yamba <br/> Department of Meteorology and Climate Science <br/>
  Kwame Nkrumah University of Science and Technology
baseurl: "" # leave empty for user.github.io sites
url: "https://yamba.github.io"
github_username: yamba
orcid: 0000-0002-0486-9921

# ------------------------------------------
# Theme and appearance
# ------------------------------------------
theme: minima  # 
minima:
  skin: classic
  date_format: "%Y %b %-d"

# ------------------------------------------
# Plugins supported by GitHub Pages
# ------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# ------------------------------------------
# Author information
# ------------------------------------------
author: "Edmund Ilimoan Yamba"

# ------------------------------------------
# Pagination settings
# ------------------------------------------
paginate: 5
paginate_path: "/page:num/"

# ------------------------------------------
# Collections (custom folders)
# ------------------------------------------
collections:
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  people:
    output: true
    permalink: /people/:path/

# ------------------------------------------
# Announcements & latest posts
# ------------------------------------------
announcements:
  enabled: true
  scrollable: true
  limit: 5

latest_posts:
  enabled: true
  scrollable: true
  limit: 3

# ------------------------------------------
# Header pages (menu navigation)
# ------------------------------------------
header_pages:
  - index.md
  - research.md
  - people.md
  - openings.md
  - publications.md
  - news.md

# ------------------------------------------
# Exclude unnecessary files from build
# ------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
